version: '2'
services:
  app:
    build: ./
    volumes:
      - '.:/app'
      - npm-app:/app/node_modules
    ports:
      - '5300:5300'
    command: bash -c 'npm start'

volumes:
  npm-app:
    driver: local
